from enum import Enum


class Variable(Enum):
    CUSTO_MARGINAL_OPERACAO = "CMO"
    CUSTO_GERACAO_TERMICA = "CTER"
    CUSTO_OPERACAO = "COP"
    ENERGIA_NATURAL_AFLUENTE = "ENA"
    ENERGIA_ARMAZENADA_ABSOLUTA = "EARM"
    ENERGIA_ARMAZENADA_PERCENTUAL = "EARP"
    GERACAO_TERMICA = "GTER"
